title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

# Raquel Babb

```
Title: [My Python Repository]
Description: [A repo housing Python graphing basics and more.]
```

## Link to My Repository

[My Repository](https://babbra91.github.io)

![A Photo of Me](/Pics/Selfie_Resizedv2.PNG)

### Files

This is content I've developed for my course:

- [Python Graphing Basics](https://github.com/babbra91/babbra91.github.io/blob/master/PythonGraphs/BasicGraphAssignment.ipynb)
- [HTML Python Graphing Basics](https://github.com/babbra91/babbra91.github.io/blob/master/PythonGraphs/BasicGraphAssignment.html)
